@host = localhost:8000

###
# // Get healthchecker
GET http://{{host}}/api/healthchecker HTTP/1.1 
content-type: application/json
###

###
// Create Profile 
POST http://{{host}}/api/auth/register HTTP/1.1 
content-type: application/json

{
    "name":"Harish",
    "email":"hkokcha@gmail.com",
    "password":"abc12311",
    "passwordConfirm":"abc12311",
    "photo":"sadf"
}


###
// Create Profile 
POST http://{{host}}/api/auth/registeration HTTP/1.1 
content-type: application/json

{
    "name":"Harish",
    "mobile":"9996838491"
}


###
// Login User
POST http://{{host}}/api/auth/login HTTP/1.1 
content-type: application/json

{
    "name":"Harish",
    "email":"hkokcha@gmail.com",
    "password":"abc12311",
    "passwordConfirm":"abc12311",
    "photo":"sadf"
}

###
# //logout 
GET http://{{host}}/api/auth/logout HTTP/1.1 
content-type: application/json

###
# // Get healthchecker
GET http://{{host}}/api/auth/refresh HTTP/1.1 
content-type: application/json


###
// Generate OTP
POST http://{{host}}/api/auth/generateotp HTTP/1.1 
content-type: application/json

{
    "user_mobile": "8898889992"
}

###
// Verify OTP
POST http://{{host}}/api/auth/verifyotp HTTP/1.1 
content-type: application/json

{
    "user_mobile": "8898889992",
    "user_otp": "123456"
    
}


###
// Update User
POST http://{{host}}/api/auth/updateUser HTTP/1.1 
content-type: application/json 
Authorization: "Bearer
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQyNjU3MTEsImlhdCI6MTcwNDI2NDgxMSwibmJmIjoxNzA0MjY0ODExLCJzdWIiOiIxIn0.D_R0Rrd2iwcuGvov7rqlFNbJ4fgL6HYAbHs5p3LN1JKwd6viOlXNrFjToMR0tHMlYtWi7XFKQPbJUgq1M58__A"

{
    "id":2,
    "mobile":"8898889992",
    "name":"Kapil kokvg"
}